# Generated by Django 4.2.7 on 2025-08-06 06:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('delivery_date', models.DateField()),
                ('junction', models.CharField(choices=[('vyttila_delivery', 'Vyttila (Delivery)'), ('kakkanad_delivery', 'Kakkanad (Delivery)'), ('edappally_delivery', 'Edappally (Delivery)'), ('palarivattom_delivery', 'Palarivattom (Delivery)'), ('pickup', 'Pickup Only')], max_length=30)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('maps_link', models.URLField(blank=True, null=True)),
                ('items', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_screenshot_url', models.URLField(blank=True, null=True)),
                ('verification_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_row_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('current_step', models.CharField(choices=[('start', 'Start'), ('date_selection', 'Date Selection'), ('junction_selection', 'Junction Selection'), ('menu_selection', 'Menu Selection'), ('delivery_details', 'Delivery Details'), ('payment_qr', 'Payment QR'), ('payment_screenshot', 'Payment Screenshot'), ('completed', 'Completed')], default='start', max_length=20)),
                ('selected_date', models.DateField(blank=True, null=True)),
                ('selected_junction', models.CharField(blank=True, max_length=30)),
                ('selected_items', models.TextField(blank=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('maps_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_interaction', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.order')),
            ],
            options={
                'ordering': ['-last_interaction'],
            },
        ),
    ]
